# Port can be overridden by using -p if running development flask
#port: 9631

icinga2:
  # The url to the Monitor server
  url: https://127.0.0.1:5665
  user: root
  passwd: cf593406ffcfd2ef
  metric_prefix: icinga2
  # Example of custom vars that should be added as labels and how to be translated
  custom_vars:
    # Specify which custom_vars to extract from Monitor
    - env:
        # Name of the label in Prometheus
        label_name: environment
    - site:
        label_name: dc

logger:
  # Path and name for the log file. If not set send to stdout
  logfile: /var/tmp/icinga2-exporter.log
  # Log level
  level: INFO